# Generated by Django 5.2.6 on 2025-09-13 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 9, 13, 1, 12, 29, 313524)),
        ),
    ]
