# Generated by Django 5.2.6 on 2025-09-13 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_goal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 9, 13, 1, 13, 17, 777468, tzinfo=datetime.timezone.utc)),
        ),
    ]
