# Generated by Django 5.2.6 on 2025-09-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_goal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.TextField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Minor', 'Minor')], default='Primary'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
