# Generated by Django 5.2.6 on 2025-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_goal_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='logged_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
